const data = [
  {name: "Bath", country: "UK", count: 4, minYear: 1706},
  {name: "Billund", country: "Denmark", count: 1, minYear: 1924},
  {name: "Brighton_and_Hove", country: "UK", count: 6, minYear: 1841},
  {name: "Copenhagen", country: "Denmark", count: 3, minYear: 1756},
  {name: "Denmark", country: "null", count: 4, minYear: 1756},
  {name: "Istanbul", country: "Turkey", count: 8, minYear: 1858},
  {name: "London", country: "UK", count: 216, minYear: 1580},
  {name: "Manchester", country: "UK", count: 3, minYear: 1832},
  {name: "Middlesex", country: "UK", count: 964, minYear: 1565},
  {name: "Perm", country: "Russia", count: 1, minYear: 2010},
  {name: "Russia", country: "null", count: 1, minYear: 2010},
  {name: "Slough", country: "UK", count: 1, minYear: 1936},
  {name: "Spelthorne", country: "UK", count: 1, minYear: 1880},
  {name: "Turkey", country: "null", count: 8, minYear: 1858},
  {name: "UK", country: "null", count: 1099, minYear: 1565},
  {name: "Windsor_and_Maidenhead", country: "UK", count: 21, minYear: 1812},
  {name: "Wolverhampton", country: "UK", count: 57, minYear: 1761},
  {name: "World", country: "null", count: 1101, minYear: 1565},
]
